{% set name = "lenskit-implicit" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lenskit_implicit-{{ version }}.tar.gz
  sha256: d6d50dc99ead9c344649fc7e0d8f86738617084ff06bbe3fc091be2098c440b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - lenskit ==0.14.*
    - implicit >=0.6.1

test:
  imports:
    - lenskit_implicit
  commands:
    - python -c "import lenskit_implicit"
  requires:
    - pip

about:
  summary: LensKit wrappers for the Implicit package.
  home: https://lkpy.readthedocs.io/projects/lenskit-implicit/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mdekstrand
